var stringSimilarity = require("string-similarity");
var tokenizer = require("sbd");

const p = `
A matador evading a bull in Cancún, Mexico, 2012.
Cancún Underwater Museum
Benito Juárez (Cancún)
Delta Air Lines Atlanta, Austin, Boston, Cancún, Cincinnati, Columbus–Glenn, Dallas/Fort Worth, Denver, Detroit, Guatemala City, Honolulu, Indianapolis, Kahului, Kailua–Kona, Kansas City, Las Vegas, Lihue, Memphis, Mexico City, Minneapolis/St. Paul, Nashville, New Orleans, New York–JFK, Orlando, Paris–Charles de Gaulle, Portland (OR), Puerto Vallarta, Raleigh/Durham, Salt Lake City, San Francisco, San José (CR), San José del Cabo, Seattle/Tacoma, Shanghai–Pudong, Sydney, Tampa, Tokyo–Haneda, Washington–National
Seasonal: Cancún 
United Airlines Boston, Cancún, Chicago–O'Hare, Cleveland, Denver, Guatemala City, Hilo, Honolulu, Houston–Intercontinental, Kahului, Kailua–Kona, Las Vegas, Lihue, London–Heathrow, Melbourne, Newark, Orlando, San Francisco, San Salvador, Shanghai–Pudong, Sydney, Tokyo–Haneda (begins September 8, 2020), Tokyo–Narita, Washington–Dulles
Volaris Aguascalientes, Cancún, Durango, Guadalajara, León/Del Bajío, Mexico City, Morelia, Oaxaca, Uruapan, Zacatecas 
6), hydrofluorocarbons (HFCs), and perfluorocarbons (PFCs)) are the major anthropogenic greenhouse gases,:147 and are regulated under the Kyoto Protocol international treaty, which came into force in 2005. Emissions limitations specified in the Kyoto Protocol expired in 2012. The Cancún agreement, agreed on in 2010, includes voluntary pledges made by 76 countries to control emissions. At the time of the agreement, these 76 countries were collectively responsible for 85% of annual global emissions.
King, D.; et al. (July 2011), \"Copenhagen and Cancún\", International climate change negotiations: Key lessons and next steps, Oxford: Smith School of Enterprise and the Environment, University of Oxford, p. 12, doi:10.4210/ssee.pbs.2011.0003 (inactive 8 June 2020), archived from the original on 1 August 2013 \"PDF available\" (PDF). Archived from the original (PDF) on 13 January 2012.
A new First Class bus station was opened in the northwest of the city, serving many Mexican travelers as well as backpackers especially from Europe. The bus station is served by the Cristobal Colon, Maya de Oro, ADO and Rapidos del Sur lines. Main destinations are Mexico, Puebla, Veracruz, Oaxaca, Tapachula, San Cristóbal, Villahermosa, Mérida and Cancún.
In 1526 Spanish Conquistador Francisco de Montejo (a veteran of the Grijalva and Cortés expeditions) successfully petitioned the King of Spain for a charter to conquer Yucatán. His first campaign in 1527, which covered much of the Yucatán Peninsula, decimated his forces but ended with the establishment of a small fort at Xaman Haʼ, south of what is today Cancún. Montejo returned to Yucatán in 1531 with reinforcements and established his main base at Campeche on the west coast. He sent his son, Francisco Montejo The Younger, in late 1532 to conquer the interior of the Yucatán Peninsula from the north. The objective from the beginning was to go to Chichén Itzá and establish a capital.
In 1972, Mexico enacted the Ley Federal Sobre Monumentos y Zonas Arqueológicas, Artísticas e Históricas (Federal Law over Monuments and Archeological, Artistic and Historic Sites) that put all the nation's pre-Columbian monuments, including those at Chichen Itza, under federal ownership. There were now hundreds, if not thousands, of visitors every year to Chichen Itza, and more were expected with the development of the Cancún resort area to the east.
Chichen Itza, a UNESCO World Heritage Site, is the second-most visited of Mexico's archaeological sites. The archaeological site draws many visitors from the popular tourist resort of Cancún, who make a day trip on tour buses.
 Cancún, Quintana Roo, Mexico
Today, Villahermosa is a modern city and one of the most important commercial points in the long stretch of territory between Mexico City and Cancún—perhaps second only to Mérida in Yucatán.
Cancún Underwater Museum
 Cancún
^ Delegatarios de países megadiversos. \"Declaración de Cancún de países megadiversos afínes\" (PDF) (in Spanish). inecc.gob.mx. Retrieved 9 March 2014.
Mexico lies squarely within the hurricane belt, and all regions of both coasts are susceptible to these storms from June through November. Hurricanes on the Pacific coast are often less violent than those affecting Mexico's eastern coastline. Several hurricanes per year strike the Caribbean and Gulf of Mexico coastline, however, and these storms bring high winds, heavy rain, extensive damage, and occasional loss of life. Hurricane Gilbert passed directly over Cancún in September 1988, with winds in excess of 200 kilometers per hour (124 mph), producing major damage to hotels in the resort area. It then struck northeast Mexico, where flooding from the heavy rain killed dozens in the Monterrey area and caused extensive damage to livestock and vegetable crops.
^ \"Anuncian reactivación del vuelo Monterrey-Nueva York de Aeroméxico\". Gobierno del Estado de Nuevo León, México. 2005. Archived from the original on March 4, 2014. Retrieved July 6, 2008. Cantú Valderrama añadió que con esto, fuera de la Ciudad de México y de los viajes charters a Cancún, Quintana Roo, Monterrey es el aeropuerto más importante en el interior de la República.
^ \"AG-2004-RES-05: Appointment of Interpol External Auditor\" (PDF). Cancún: INTERPOL. 8 October 2004. Retrieved 31 March 2017.
Cancún Underwater Museum
Cancún Underwater Museum
Cancún Underwater Museum
2016 – Cancún (L)
In the late historic and early modern eras, the Yucatán Peninsula was largely a cattle ranching, logging, chicle and henequen production area. Since the 1970s (and the fall of the world henequen and chicle markets due to the advent of synthetic substitutes), the Yucatán Peninsula has reoriented its economy towards tourism, especially in the Mexican state of Quintana Roo. Once a small fishing village, Cancún in the northeast of the peninsula has grown into a thriving city. The Riviera Maya, which stretches along the east coast of the peninsula between Cancún and Tulum, houses over 50,000 beds. The best-known locations are the former fishing town of Playa del Carmen, the ecological parks Xcaret and Xel-Há and the Maya ruins of Tulum and Coba.
Cancún Underwater Museum
The arrest and extradition of Osiel Cárdenas, however, caused several top lieutenants from both the Gulf Cartel and Los Zetas to fight over important drug corridors to the United States, especially in the cities of Matamoros, Nuevo Laredo, Reynosa, and Tampico—all situated in Tamaulipas state. They also fought for coastal cities Acapulco and Cancún; the state capital of Monterrey, and the states of Veracruz and San Luis Potosí. Using violence and intimidation, Heriberto Lazcano took control of both Los Zetas and the Gulf Cartel after Cárdenas’ extradition. Lieutenants who were once loyal to Cárdenas began following Lazcano's orders. He tried to reorganize the cartel by appointing several lieutenants to control specific territories. Morales Treviño was appointed to oversee Nuevo León; Jorge Eduardo Costilla Sánchez in Matamoros; Héctor Manuel Sauceda Gamboa, nicknamed El Karis, took control of Nuevo Laredo; Gregorio Sauceda Gamboa, known as El Goyo, along with his brother Arturo, took control of the Reynosa plaza; Arturo Basurto Peña, alias El Grande, and Iván Velásquez Caballero alias El Talibán took control of Quintana Roo and Guerrero; and Alberto Sánchez Hinojosa, alias Comandante Castillo, took over Tabasco. However, continual disagreement was leading the Gulf Cartel and Los Zetas into an inevitable rupture.
Cancún Underwater Museum
1975: Cancún
The International Energy Agency estimates that US$197 billion is required by states in the developing world above and beyond the underlying investments needed by various sectors regardless of climate considerations, this is twice the amount promised by the developed world at the UN Framework Convention on Climate Change (UNFCCC) Cancún Agreements. Thus, a new method is being developed to help ensure that funding is available for climate change mitigation. This involves financial leveraging, whereby public financing is used to encourage private investment.
The Doha round of World Trade Organization negotiations aimed to lower barriers to trade around the world, with a focus on making trade fairer for developing countries. Talks have been hung over a divide between the rich developed countries, represented by the G20, and the major developing countries. Agricultural subsidies are the most significant issue upon which agreement has been the hardest to negotiate. By contrast, there was much agreement on trade facilitation and capacity building. The Doha round began in Doha, Qatar, and negotiations were continued in: Cancún, Mexico; Geneva, Switzerland; and Paris, France and Hong Kong.
Cancún Underwater Museum
Cancún
Cancún
Cancún
Cancún (Mexico)
Website www.cancun.gob.mx
Cancún (/kænˈkuːn/ or /kɑːn-/;Spanish pronunciation:  pronunciation (help·info)) is a city in southeast Mexico on the northeast coast of the Yucatán Peninsula in the Mexican state of Quintana Roo. It is a significant tourist destination in Mexico and the seat of the municipality of Benito Juárez. The city is on the Caribbean Sea and is one of Mexico's easternmost points.
Cancún is just north of Mexico's Caribbean coast resort band known as the Riviera Maya. In older English-language documents, the city’s name is sometimes spelled \"Cancoon\", an attempt to convey the sound of the name.
4 Cancún Airport's old Control Tower Memorial
There are two possible translations of Cancún, based on the Mayan pronunciation kaan kun. The first translation is \"nest of snakes\". The second version and less accepted is \"place of the golden snake\".
The shield of the municipality of Benito Juárez, which represents the city of Cancún, was designed by the Mexican-American artist Joe Vera.
As documented in the earliest colonial sources, Cancún was originally known to its Maya inhabitants as Nizuc (Yucatec Maya ) meaning either \"promontory\" or \"point of grass\". In the years after the Conquest, much of the Maya population died off or left as a result of disease, warfare, piracy, and famines, leaving only small settlements on Isla Mujeres and Cozumel Island.
The name Cancún, Cancum or Cankun first appears on 18th-century maps. The meaning of Cancún is unknown, and it is also unknown whether the name is of Maya origin. If it is of Maya origin, possible translations include \"Place/Seat/Throne of the Snake\" or \"Enchanted Snake\". Snake iconography was prevalent at the pre-Columbian site of Nizuc.
When development of the area as a resort was started on January 23, 1970, Isla Cancún had only three residents, all caretakers of the coconut plantation of Don José de Jesús Lima Gutiérrez, who lived on Isla Mujeres. Some 117 people lived in nearby Puerto Juárez, a fishing village and military base.
Due to the reluctance of investors to gamble on an unknown area, the Mexican federal government financed the first nine hotels. The first financed hotel was a Hyatt, Cancún Caribe, but the first hotel built was the Playa Blanca, which later became a Blue Bay hotel. It is now named Temptation Resort. At the time it was an elite destination, famous for its virgin white sand beaches.
The city began as a tourism project in 1974 as an Integrally Planned Center, a pioneer of FONATUR (Fondo Nacional de Fomento al Turismo, National Fund for Tourism Development), formerly known as INFRATUR. Since then, it has undergone a comprehensive transformation from being a fisherman's island surrounded by virgin forest and undiscovered shores to being one of the two most well-known Mexican resorts, along with Acapulco. The World Tourism Organization (WTO), through its foundation UNWTO-Themis, awarded the Best of the Best award \"for excellence and good governance\" to the Trust for Tourism Promotion of Cancún on February 3, 2007. This award ensured Cancún the ongoing support of the Department of Education and Knowledge Management of the WTO.
Cancún Airport's old Control Tower Memorial
One of Cancún designs before zoning
There are some small Mayan vestiges of the pre-Columbian Maya civilization in Cancún. El Rey (Las Ruinas del Rey) is located in the Hotel Zone. El Meco, a more substantial site, is found on the mainland just outside the city limits on the road north to Punta Sam.
Cancún is also served by three private bus lines that connect it to the downtown area and the \"hotel zone\" as well as more distant destinations such as Playa del Carmen and Tulum.
Cancún has a tropical climate, specifically a tropical wet and dry climate (Köppen Aw), with little difference between seasons, but pronounced rainy and dry seasons. The city is hot year-round, and moderated by onshore trade winds, with an annual mean temperature of 27.1 °C (80.8 °F). Unlike inland areas of the Yucatán Peninsula, sea breezes restrict high temperatures from reaching 36 °C (97 °F) on most afternoons. Annual rainfall is around 1,340 millimetres (52.8 in), falling on 115 days per year.
Climate data for Cancún
The tropical storm season lasts from May to December, the rainy season extends into January with peak precipitation in October. February to early May tend to be drier with only occasional scattered showers. Cancún is located in one of the main Caribbean hurricane impact areas. Although large hurricanes are rare, they have struck near to Cancún in recent years, Hurricane Wilma in 2005 being the largest. Hurricane Gilbert made a devastating direct hit on Cancún in September 1988 and the tourist hotels needed to be rebuilt. In both cases, federal, state and municipal authorities were well prepared to deal with most of the effects on tourists and local residents. Hurricane Dean in 2007 also made its mark on the city of Cancún.
1988's Hurricane Gilbert was the second most intense hurricane ever observed in the Atlantic basin. It landed on the Yucatán peninsula after crossing over the island of Cozumel. In the Cancún region, a loss of $87 million (1989 USD) due to a decline in tourism was estimated for the months October, November and December in 1988.
On October 21, 2005, Hurricane Wilma made landfall on Mexico's Yucatán Peninsula as a powerful Category 4 hurricane, with strong winds in excess of 150 mph (240 km/h). The hurricane's eye first passed over the island of Cozumel, and then made an official landfall near Playa del Carmen in the state of Quintana Roo at around 11 p.m. local time on October 21 with winds near 140 mph (230 km/h). Portions of the island of Cozumel experienced the calm eye of Wilma for several hours with some blue skies and sunshine visible at times. The eye slowly drifted northward, with the center passing just to the west of Cancún, Quintana Roo.
Two years later after Hurricane Wilma, in 2007, Hurricane Dean made landfall as a Category 5 storm in Majahual, 190 miles (310 km) to the south of Cancún. Fierce winds at the edge of Dean's impact cone stripped sand off 7.5 miles (12.1 km) of beaches from Punta Cancún (Camino Real Hotel) to Punta Nizuc (Club Med).
Although Cancún is better known as a travel and tourism destination, some colleges and universities offer higher education to both Mexican and foreign students. Private schools in Cancún include Centro Educativo Monteverde, International American School of Cancun, Instituto Césare, and Centro Educativo Diuni.
The city has been home to Atlante F.C., a traditional Mexico City football club, since 2007. Atlante F.C. was moved to Cancún's Andrés Quintana Roo Stadium when that stadium opened. Its games had low attendance at its previous stadium, Azteca Stadium, which it had been renting. The team currently plays in the Ascenso MX, the second level of the Mexican football pyramid. The city is also home to the Pioneros de Cancún, who play in the third division Liga Premier de México.
The city has been devastated by violent acts related to drug trafficking. Between 2013 and 2016 there were 76 murders: 31 in 2016, and at least 193 in 2017, the vast majority related to drug trafficking. Most have occurred in the urban nucleus, and there have been various violent episodes with firearms in the so-called \"Zona Hotelera\". Beginning in 2018 with a high wave of violence, Cancún is above the national average in homicides. In January 2018 alone there were 33 homicides, triple the number from January 2017.
The violent acts have begun to put pressure on the tourism industry, where in January 2019, Cancún saw its first decrease in international passengers in seven years.
In the 21st century, Cancún had largely avoided the bloodshed associated with the trade of illegal drugs, but is known for its retail drug sales to tourists as well as for being a center of money laundering.
The links with Cancún date from the 1990s and early 2000s, when the area was controlled by the Juárez and Gulf drug cartels. In recent years Los Zetas, a group that broke away from the Gulf Cartel, has taken control of many smuggling routes through the Yucatán, according to the U.S. Drug Enforcement Administration.
Crowded beach at Cancún Island
The beach in Cancún, México.
Cancún Underwater Museum
^ \"Cancún\". Merriam-Webster Dictionary. Retrieved August 11, 2016.
^ \"OMT concede premio excelencia a la promoción turística de Cancún (México)\" (in Spanish). ES: El Economista. February 3, 2007. Archived from the original on July 22, 2011. Retrieved June 17, 2011.
^ Varillas, Adriana (August 19, 2013). \"Centro de Cancún, tan mexicano como cosmopolita\". El Periodico de Quintana Roo. Archived from the original on October 6, 2014. Retrieved October 6, 2014.
^  Archived July 30, 2009, at the Wayback Machine A proper Maya spelling of Nizuc may be “Ni’ su’uk” which translates to “promontory” or “point of grass”-Source-Some Historic Notes and Observations on Isla Cancún, Quintana Roo], published at FAMSI by Andrews, Anthony P.
^ \"Government of Mexico, Cancún 2014\". cancun.gob.mx. Archived from the original on November 11, 2013. Retrieved September 2, 2014.
^ \"Snake iconography was prevalent at the pre-Columbian site of Nizuc-Source- Historic Notes and Observations on Isla Cancún, Quintana Roo\" (PDF). famsi.org. FAMSI. p. 5. Archived (PDF) from the original on July 30, 2009. Retrieved May 7, 2010.
^ http://www.revistapioneros.com/la-antigua-torre-de-control-simbolo-de-la-fundacion-de-cancun/ Archived May 27, 2015, at the Wayback Machine Cancún's Airport Old Control Tower.
^  Archived October 8, 2009, at the Wayback Machine Cancún Weather
^  Archived July 12, 2011, at the Wayback Machine Hurricane Dean On Course for Cancún
^ a b \"Se disparan 162% los homicidios en Cancún\". www.milenio.com. Archived from the original on February 6, 2018. Retrieved February 2, 2018.
^ \"Abaten a tiros a mujer en Cancún, llegan a 193 asesinatos este año\". yucatanalamano.com. Archived from the original on January 8, 2018. Retrieved February 2, 2018.
^ a b \"En 2017, crimen organizado mató a 111 en Cancún\". www.milenio.com. Archived from the original on January 31, 2018. Retrieved February 2, 2018.
^ \"Se disparan 300% los homicidios en Cancún - La Palabra del Caribe - Periodismo con ética - Noticias de Quintana Roo\". lapalabradelcaribe.com. February 1, 2018. Archived from the original on February 3, 2018. Retrieved February 2, 2018.
^ \"Baja por primera vez en 7 anos Illegada de turistas internacionales a Cancún\". February 24, 2019.
 Wikimedia Commons has media related to Cancún.
Cancún at Curlie
Benito Juárez (Cancún)
Cancún Underwater Museum
Cancún Underwater Museum
Cancún, Mexico (Aw)
Cancún Underwater Museum
Cancún Underwater Museum
The coastlines of Mexico harbor many stretches of beaches that are frequented by sunbathers and other visitors. According to national law, the entirety of the coastlines are under federal ownership, that is, all beaches in the country are public. On the Yucatán peninsula, one of the most popular beach destinations is the resort town of Cancún, especially among university students during spring break. Just offshore is the beach island of Isla Mujeres, and to the east is the Isla Holbox. To the south of Cancun is the coastal strip called Riviera Maya which includes the beach town of Playa del Carmen and the ecological parks of Xcaret and Xel-Há. A day trip to the south of Cancún is the historic port of Tulum. In addition to its beaches, the town of Tulum is notable for its cliff-side Mayan ruins.
Starting in the late nineteenth century, Mexico was one of the first Latin American countries to promote railway development, and the network covers 30,952 km (19,233 mi). The Secretary of Communications and Transport of Mexico proposed a high-speed rail link that will transport its passengers from Mexico City to Guadalajara, Jalisco. The train, which will travel at 300 kilometres per hour (190 miles per hour), will allow passengers to travel from Mexico City to Guadalajara in just 2 hours. The whole project was projected to cost 240 billion pesos, or about 25 billion US$ and is being paid for jointly by the Mexican government and the local private sector including the wealthiest man in the world, Mexico's billionaire business tycoon Carlos Slim. The government of the state of Yucatán is also funding the construction of a high speed line connecting the cities of Cozumel to Mérida and Chichen Itza and Cancún.
 Cancún in Mexico
Cancún Underwater Museum
Cancún Underwater Museum
Cancún Underwater Museum
Cancún Underwater Museum
Air France Aberdeen, Abidjan, Abuja, Accra, Alicante, Algiers, Amman–Queen Alia, Amsterdam, Antananarivo, Athens, Atlanta, Bamako, Bangkok–Suvarnabhumi, Bangui, Barcelona, Basel/Mulhouse, Beijing–Capital, Beirut, Belgrade, Bengaluru, Bergen, Berlin–Tegel, Biarritz, Bilbao, Billund, Birmingham, Bogotá, Bologna, Bordeaux, Boston, Brazzaville, Bremen, Brest, Bucharest, Budapest, Buenos Aires–Ezeiza, Cairo, Cancún, Cape Town, Caracas, Casablanca, Catania, Cayenne, Chennai (resumes 27 October 2020), Chicago–O'Hare, Clermont-Ferrand, Conakry, Copenhagen, Cotonou, Dakar–Diass, Delhi, Detroit, Djibouti, Douala, Dubai–International, Dublin, Düsseldorf, Edinburgh, Faro, Florence, Fortaleza, Frankfurt, Freetown, Geneva, Genoa, Gothenburg, Hamburg, Hanover, Havana, Ho Chi Minh City, Hong Kong, Houston–Intercontinental, Istanbul, Johannesburg–O. R. Tambo, Kiev–Boryspil, Kinshasa–N'djili, Kraków, Lagos, Libreville, Lima, Lisbon, Ljubljana, Lomé, London–Heathrow, Lorient, Los Angeles, Luanda, Lyon, Madrid, Malabo, Malaga, Manchester, Marrakesh, Marseille, Mauritius, Mexico City, Miami, Milan–Linate, Milan–Malpensa, Monrovia, Montpellier, Montréal–Trudeau, Moscow–Sheremetyevo, Mumbai, Munich, Nairobi–Jomo Kenyatta, Nantes, Naples, N'Djamena, Newcastle upon Tyne, New York–JFK, Niamey, Nice, Nouakchott, Nuremberg, Oran, Osaka–Kansai, Oslo–Gardermoen, Ouagadougou, Palma de Mallorca, Panama City–Tocumen, Papeete, Pau, Pointe-Noire, Port Harcourt, Porto, Prague, Punta Cana, Quito, Rabat, Rennes, Rio de Janeiro–Galeão, Rome–Fiumicino, Saint-Denis de la Réunion, Saint Petersburg, San Francisco, San José de Costa Rica, Santiago de Chile, Santo Domingo–Las Américas, São Paulo–Guarulhos, Seattle/Tacoma, Seoul–Incheon, Seville, Shanghai–Pudong, Singapore, St. Maarten, Stockholm–Arlanda, Stuttgart, Taipei–Taoyuan, Tel Aviv, Tokyo–Haneda, Tokyo–Narita, Toronto–Pearson, Toulouse, Tunis, Turin, Valencia, Vancouver, Venice, Vienna, Warsaw–Chopin, Washington–Dulles, Wrocław, Yaoundé, Yerevan, Zagreb, Zurich
^ (Extrapolation from the 16th-century Spanish, 'Cali' ˈkali a rich agricultural area – geographical sunny climate. also 1536, Cauca River, linking Cali, important for higher population agriculture and cattle raising & Colombia's coffee is produced in the adjacent uplands. Britannica Concise Encyclopedia. 'Cali', city, metropolis, urban center. Pearson Education 2006. \"Calica\", Yucatán place name called rock pit, a port an hour south of Cancún. Sp. root: \"Cal\", limestone. Also today, 'Calicuas', supporting cylinder or enclosing ring, or moveable prop as in holding a strut)
 Cancún, Quintana Roo, Mexico - November 25, 1975
The beach in Cancún, México.
Cancún Underwater Museum
Cancún Underwater Museum
^ International destinations include London, Toronto and Cancún, Mexico (seasonal). American Airlines operates the daily service to London Heathrow. Delta Air Lines announced in November 2008 that service from RDU to Paris, France would begin in June 2009.[https://web.archive.org/web/20101127105138/http://rdu.com/news/2008/release_011708.htm Raleigh-Durham International Airport|date=March 25, 2008 }}
The Querétaro metropolitan area comprises the municipalities of Querétaro, Corregidora, El Marqués and Huimilpan with a total population in 2010 of 1,097,028. According to data from the National Population Council, Querétaro is the 10th largest metro area in Mexico, as well as the 128th largest in the Americas. The metropolitan area of Querétaro has seen a population growth of between 3.65 and 5.54 percent per year since the second half of the 1990s, which makes it the fifth fastest-growing in the country behind Cancún, Tijuana, Puerto Vallarta, Ciudad Juárez and Nuevo Laredo. The population of the metro area in 2005 was 738,921, with 58% living outside of Querétaro city proper. The municipality of Corregidora has the highest rate of population growth in the state at 5.54%. Most of the population growth is due to migration with people coming here from Mexico City, Mexico State and Guanajuato. It is estimated that in 2005, 10,465 people migrated to the metropolitan area.
Cancún Underwater Museum
Cancún Underwater Museum
Cancún Underwater Museum
^ (Extrapolation from the 16th-century Spanish, 'Cali' ˈkali a rich agricultural area—geographical sunny climate. also 1536, Cauca River, linking Cali, important for higher population agriculture and cattle raising & Colombia's coffee is produced in the adjacent uplands. Britannica Concise Encyclopedia. 'Cali', city, metropolis, urban center. Pearson Education 2006. \"Calica\", Yucatán place name called rock pit, a port an hour south of Cancún. Sp. root: \"Cal\", limestone. Also today, 'Calicuas', supporting cylinder or enclosing ring, or moveable prop as in holding a strut)
While much of the glitz and glamour that made Acapulco famous still remains, from the latter 20th century on, the city has also taken on other less-positive reputations. Some consider it a passé resort, eclipsed by the newer Cancún and Cabo San Lucas. Over the years, a number of problems have developed here, especially in the bay and the older sections of the city. The large number of wandering vendors on the beaches, who offer everything from newspapers to massages, are a recognized problem. It is a bother to tourists who simply want to relax on the beach, but the government says it is difficult to eradicate, as there is a lot of unemployment and poverty here. Around the city are many small shantytowns that cling to the mountainsides, populated by migrants who have come here looking for work. In the last decade, drug-related violence has caused massive problems for the local tourism trade.
In the late 1990s and early 2000s, Cancún had been favored as the spring break destination of choice. However, Cancún has taken some steps to control the reckless behavior associated with the event, and students have been looking for someplace new. This led many more to choose Acapulco, in spite of the fact that for many travelers, the flight is longer and more expensive than to Cancún. Many were attracted by the glitzy hotels on the south side and Acapulco's famous nightlife. In 2008, 22,500 students came to Acapulco for spring break. Hotels did not get that many in 2009, due mostly to the economic situation in the United States, and partially because of scares of drug-related violence.
Cancún Underwater Museum
Cancún Underwater Museum
Cancún Underwater Museum
American Airlines Albuquerque, Atlanta, Austin, Baltimore, Boston, Cancún, Charlotte, Dallas/Fort Worth, Denver, Fort Lauderdale, Fort Myers, Hartford, Houston–Intercontinental, Indianapolis, Kansas City, Las Vegas, London–Heathrow, Los Angeles, Miami, Minneapolis/St. Paul, Newark, New Orleans, New York–JFK, New York–LaGuardia, Orange County (CA), Orlando, Philadelphia, Phoenix–Sky Harbor, Pittsburgh, Portland (OR), Raleigh/Durham, Reno/Tahoe, Sacramento, St. Louis, Salt Lake City, San Antonio, San Diego, San Francisco, San Jose (CA), San Juan, Seattle/Tacoma, Tampa, Toronto–Pearson, Tucson, Washington–National, West Palm Beach
Frontier Airlines Cancún, Denver, Fort Myers, Las Vegas, Miami, Newark, Orlando, Pensacola, Philadelphia, Phoenix–Sky Harbor, Punta Cana, San Juan, Sarasota, Tampa
Spirit Airlines Atlanta, Austin, Baltimore, Cancún, Dallas/Fort Worth, Denver, Fort Lauderdale, Fort Myers, Houston–Intercontinental, Las Vegas, Los Angeles, New Orleans, New York–LaGuardia, Orlando, San Diego, Tampa
United Airlines Albany, Amsterdam, Aruba, Atlanta, Austin, Baltimore, Beijing–Capital, Belize City, Boston, Bozeman, Brussels, Buffalo, Calgary, Cancún, Cedar Rapids/Iowa City, Charleston (SC), Charlotte, Cincinnati, Cleveland, Columbus–Glenn, Dallas/Fort Worth, Denver, Des Moines, Detroit, Duluth, Eugene (OR), Fort Lauderdale, Fort Myers, Frankfurt, Fresno, Grand Rapids, Harrisburg, Hartford, Hong Kong (resumes September 13, 2020), Honolulu, Houston–Intercontinental, Indianapolis, Kahului, Kansas City, Las Vegas, London–Heathrow, Los Angeles, Madison, Memphis, Mexico City, Miami, Milwaukee, Minneapolis/St. Paul, Munich, Nashville, Newark, New Orleans, New York–LaGuardia, Norfolk, Omaha, Orange County (CA), Orlando, Paris–Charles de Gaulle, Philadelphia, Phoenix–Sky Harbor, Pittsburgh, Portland (OR), Raleigh/Durham, Richmond, Rochester (NY), Sacramento, Salt Lake City, San Antonio, San Diego, San Francisco, San Jose (CA), San Juan, Santa Barbara (resumes September 8, 2020), São Paulo–Guarulhos, Sarasota, Seattle/Tacoma, Shanghai–Pudong, Spokane, Syracuse, Tampa, Tel Aviv (begins September 10, 2020), Tokyo–Haneda, Toronto–Pearson, Vancouver, Washington–Dulles, Washington–National, West Palm Beach, Zurich (begins October 24, 2020)
 Cancún
Mérida-Kantunil-Cancún (Federal 180), 4 lane road that becomes a Toll road at kantunil. It joins Mérida with Chichén Itzá, Valladolid and ultimately Cancún.
^ Fodor's 2001 Cancún, Cozumel, Yucatán Peninsula p.167. Fodor's, 2000
Delphinus Dreams Cancún
 Dolphin Discovery - Cancún, Isla Mujeres
Cancún Underwater Museum
Cancún Underwater Museum
Cancún Underwater Museum
Cancún Underwater Museum
Although until the 1960s, many indigenous communities were considered by scholars to be autonomous and economically isolated, this was never the case. Economic conditions began forcing many to migrate to work, especially in agriculture for non-indigenous. However, unlike many other migrant workers, most indigenous in Chiapas have remained strongly tied to their home communities. A study as early as the 1970s showed that 77 percent of heads of household migrated outside of the Chamula municipality as local land did not produce sufficiently to support families. In the 1970s, cuts in the price of corn forced many large landowners to convert their fields into pasture for cattle, displacing many hired laborers, cattle required less work. These agricultural laborers began to work for the government on infrastructure projects financed by oil revenue. It is estimated that in the 1980s to 1990s as many as 100,000 indigenous people moved from the mountain areas into cities in Chiapas, with some moving out of the state to Mexico City, Cancún and Villahermosa in search of employment.
Cancún
^ (Extrapolation from the 16th-century Spanish, 'Cali' ˈkali a rich agricultural area—geographical sunny climate. also 1536, Cauca River, linking Cali, important for higher population agriculture and cattle raising & Colombia's coffee is produced in the adjacent uplands. Britannica Concise Encyclopedia. 'Cali', city, metropolis, urban center. Pearson Education 2006. \"Calica\", Yucatán place name called rock pit, a port an hour south of Cancún. Sp. root: \"Cal\", limestone. Also today, 'Calicuas', supporting cylinder or enclosing ring, or moveable prop as in holding a strut)
 Cancún, Mexico
Cancún Underwater Museum
Since the earthquake, Domingo has continued to do charitable work in Mexico and other countries. After Hurricane Pauline ravaged the Pacific coast of Southern Mexico in 1997, he gave two charity concerts in Acapulco to raise money to build 150 new houses for those made homeless by the storm. In December 2003, he performed in Cancún to benefit the Ciudad de la Alegria Foundation, which provides assistance and lodging to people in need, including low-income individuals, orphans, expectant mothers, immigrants, rehabilitated legal offenders, and the terminally ill. Outside of Mexico, Domingo and Katherine Jenkins performed in a charity concert in Athens on 27 June 2007 to raise funds to aid victims of the conflict in Darfur. The concert was organized by Médecins Sans Frontières (Doctors Without Borders).
^ \"Performance in Cancún to benefit the Ciudad de la Alegria Foundation\".
Cancún Underwater Museum
Largest city Cancún
Quintana Roo is the home of the city of Cancún, the islands of Cozumel and Isla Mujeres, and the towns of Bacalar, Playa del Carmen and Akumal, as well as the ancient Maya ruins of Chacchoben, Cobá, Kohunlich, Muyil, Tulum, Xel-Há, and Xcaret. The Sian Ka'an biosphere reserve is also located in the state.
The city of Cancún is a major tourist resort in Quintana Roo
Aerial view of Cancún
The Riviera Maya is located along the Caribbean coastline, including Cancún, Playa del Carmen, Puerto Morelos, Akumal and Cozumel.
Instituto Tecnológico de Cancún, Cancún
Universidad Anáhuac Cancún, Cancún
Universidad del Caribe, Cancún
Universidad La Salle Cancún, Cancún
Universidad TecMilenio, Cancún
Estadio Andrés Quintana Roo in Cancún.
Ascenso MX. Their home ground (since 2007) is the Estadio Andrés Quintana Roo in Cancún.
After playing the 1955–2001 seasons in Mexico City and the 2002–2005 seasons in Puebla the Quintana Roo Tigers have been playing baseball with a home field at the Estadio de Béisbol Beto Ávila in Cancún since the 2006 season. The Tigers made it to the Mexican League series in 2009, but lost to the Saraperos de Saltillo 4 games to 2.
Benito Juárez (Cancún)
During the Cancún COP16 in 2010, donor countries promised an annual $100 billion by 2020 through the Green Climate Fund for developing countries to adapt to climate change. However, concrete pledges by developed countries have not been forthcoming. Emmanuel Macron (President of France) said at the 2017 United Nations Climate Change Conference in Bonn (COP 23): \"Climate change adds further injustice to an already unfair world\".
Cancún Underwater Museum
Cancún
Cancún Underwater Museum
The Doha Development Round began in 2001. The Doha Round began with a ministerial-level meeting in Doha, Qatar in 2001. The aim was to focus on the needs of developing countries. The major factors discussed include trade facilitation, services, rules of origin and dispute settlement. Special and differential treatment for the developing countries were also discussed as a major concern. Subsequent ministerial meetings took place in Cancún, Mexico (2003), and Hong Kong (2005). Related negotiations took place in Paris, France (2005), Potsdam, Germany (2007), and Geneva, Switzerland (2004, 2006, 2008). Progress in negotiations stalled after the breakdown of the July 2008 negotiations.
Cancún Underwater Museum
Cancún Underwater Museum
Cancún Underwater Museum
 Cancún, Mexico
The Belize Barrier Reef is a series of coral reefs straddling the coast of Belize, roughly 300 metres (980 ft) offshore in the north and 40 kilometres (25 mi) in the south within the country limits. The Belize Barrier Reef is a 300 kilometres (190 mi) long section of the 900 kilometres (560 mi) long Mesoamerican Barrier Reef System, which is continuous from Cancún on the northeast tip of the Yucatán Peninsula through the Riviera Maya up to Honduras making it one of the largest coral reef systems in the world.
Cancún Underwater Museum
Cancún Underwater Museum
Delta Air Lines Akron/Canton, Albany (NY), Albuquerque, Allentown, Amsterdam, Appleton, Aruba, Asheville, Augusta (GA), Austin, Baltimore, Belize City, Bermuda, Birmingham (AL), Bogotá, Bonaire, Boston, Brussels, Buenos Aires–Ezeiza, Buffalo, Burbank, Burlington (VT), Cancún, Cape Town1 (begins October 24, 2020), Cartagena, Cedar Rapids/Iowa City (IA), Charleston (SC), Charleston (WV), Charlotte, Charlottesville, Chattanooga, Chicago–Midway, Chicago–O'Hare, Cincinnati, Cleveland, Colorado Springs, Columbia (SC), Columbus–Glenn, Cozumel, Dallas/Fort Worth, Dallas–Love, Dayton, Daytona Beach, Denver, Des Moines, Destin/Fort Walton Beach, Detroit, Düsseldorf, El Paso, Fayetteville/Bentonville, Fayetteville (NC), Flint, Fort Lauderdale, Fort Myers, Frankfurt, Gainesville, Grand Cayman, Grand Rapids, Greensboro, Greenville/Spartanburg, Guadalajara, Guatemala City, Gulfport/Biloxi, Harrisburg, Hartford, Honolulu, Houston–Hobby, Houston–Intercontinental, Huntsville, Indianapolis, Jackson (MS), Jacksonville (FL), Johannesburg–O. R. Tambo, Kansas City, Key West, Kingston–Norman Manley, Knoxville, Lafayette, Lagos, Las Vegas, Lexington, Liberia (CR), Lima, Little Rock, London–Heathrow, Los Angeles, Louisville, Madison, Madrid, Managua, Melbourne (FL), Memphis, Mexico City, Miami, Milwaukee, Minneapolis/St. Paul, Mobile, Montego Bay, Monterrey, Munich, Nashville, Nassau, Newark, New Orleans, Newport News, New York–JFK, New York–LaGuardia, Norfolk, Oakland, Oklahoma City, Omaha, Ontario (CA), Orange County, Orlando, Panama City (FL), Panama City–Tocumen, Paris–Charles de Gaulle, Pensacola, Philadelphia, Phoenix–Sky Harbor, Pittsburgh, Portland (ME), Portland (OR), Providence, Providenciales, Puerto Vallarta, Punta Cana, Quito, Raleigh/Durham, Richmond, Rio de Janeiro–Galeão, Roanoke, Roatán, Rochester (NY), Rome–Fiumicino, Sacramento, St. Louis, St. Lucia–Hewanorra, St. Maarten, St. Thomas, Salt Lake City, San Antonio, San Diego, San Francisco, San Jose (CA), San José (Costa Rica), San José del Cabo, San Juan, San Pedro Sula, San Salvador, Santiago de Chile, Santo Domingo–Las Américas, São Paulo–Guarulhos, Sarasota, Savannah, Seattle/Tacoma, Seoul–Incheon, Shanghai–Pudong, Sioux Falls, Stuttgart, Syracuse, Tallahassee, Tampa, Tegucigalpa, Tokyo–Haneda, Toronto–Pearson, Tri-Cities (TN), Tucson, Tulsa, Vancouver, Washington–Dulles, Washington–National, West Palm Beach, White Plains, Wichita, Wilmington (NC)
 Cancún, Mexico
An economic downturn in Mexico caused tourists to flock to Puerto Vallarta. In 1982, the peso was devalued and Puerto Vallarta became a bargain destination for US tourists. Consequently, the mid-1980s saw a marked and rapid rise in the tourist volume. This uptick fueled additional development, for example the Marina which was started in 1986. But Puerto Vallarta's success caused other Mexican cities to take note. The early 1990s saw Mexico's government and private business develop other resort destinations, such as Ixtapa and Cancún. This took away Puerto Vallarta's exclusivity of sorts on the foreign tourist trade, and caused a slump in travel to Puerto Vallarta.
Aerial view of Cancún. Mexico is the most visited country in Latin America and 6th in the world.
Places such as Cancún, Riviera Maya, Galápagos Islands, Punta Cana, Chichen Itza, Cartagena de Indias, Cabo San Lucas, Mexico City, Machu Picchu, Margarita Island, Acapulco, San Ignacio Miní, Santo Domingo, Buenos Aires, Salar de Uyuni, Rio de Janeiro, Punta del Este, Labadee, San Juan, São Paulo, La Habana, Panama City, Iguazú Falls, Puerto Vallarta, Poás Volcano National Park, Viña del Mar, Guanajuato City, Bogotá, Santa Marta, San Andrés, San Miguel de Allende, Lima, Guadalajara, Cuzco, Ponce and Perito Moreno Glacier are popular among international visitors in the region.
Stiglitz, Joseph E. (2004). The development round of trade negotiations in the aftermath of Cancún. London, UK: Commonwealth Secretariat. ISBN 9780850928013.
Cancún, Quintana Roo, Mexico
On 28 November 2014, Chespirito died from heart failure as a complication of Parkinson's disease at the age of 85, in his home in Cancún, Quintana Roo, Mexico. Many Mexican celebrities and Chespirito's former co-stars took to Twitter to express their feelings and send their condolences to Chespirito's widow and family. Such celebrities and former co-stars included George Lopez, Eugenio Derbez, Carlos Villagran, Edgar Vivar, Ruben Aguirre, and María Antonieta de las Nieves. Chespirito is widely regarded as one of the most renowned Spanish-language comedians of the 20th century.
Cancún Underwater Museum
Cancún Underwater Museum
Cancún
Cancún Underwater Museum
Issues involving subsidies and trade barriers on such crops have become controversial in discussions of globalization. Many developing countries take the position that the current international trade system is unfair because it has caused tariffs to be lowered in industrial goods while allowing for low tariffs and agricultural subsidies for agricultural goods. This makes it difficult for a developing nation to export its goods overseas, and forces developing nations to compete with imported goods which are exported from developed nations at artificially low prices. The practice of exporting at artificially low prices is known as dumping, and is illegal in most nations. Controversy over this issue led to the collapse of the Cancún trade talks in 2003, when the Group of 22 refused to consider agenda items proposed by the European Union unless the issue of agricultural subsidies was addressed.
^ HiddenCancun.com. \"Chichen Itza - Mayan Ruins - Yucatan\". Hiddencancun.com. Retrieved 30 December 2017.
In 1999, President of Mexico Ernesto Zedillo started a program erecting giant flags across the country. Directed by the Secretariat of National Defense, the banderas monumentales (monumental flags) were placed in various cities and spots, most of which are of great significance to the nation. In a decree issued on July 1, 1999, by Zedillo, the flags were to be placed in Mexico City, Tijuana, Ciudad Juárez, and Veracruz. The decree also stipulated for the flags to measure 14.3 meters by 25 meters, which are raised on flag poles that are 50 meters high. After these initial monumental flags were created, cities such as Ensenada, Nuevo Laredo and Cancún were reported to have their own monumental flags. Smaller flags, called banderas semi-monumentales, have been erected in smaller towns and at various educational institutes.
Cancún, Quintana Roo
Cancún Underwater Museum
Cancún,go,ADO,Autobuses Del Oriente,,,"Calle Pino, SM23, MZ 1, Lt 1 y 2, Centro",,+52 55 5133-5133,+1800-009-9090,,,http://www.ado.com.mx,,,,,,,,,,,"They operate the '''ADO, ADO GL, OCC (Ómnibus Cristóbal Colón), Riviera''' and '''Platino''' bus lines, and the '''[http://www.clickbus.com.mx ClickBus.com]''' booking site."
Cancún,go,Auto Centro,,,,,,+52 999 923 9962,,,,http://www.autobusescentro.com,,,,,,,,,,2015-07-12,"operates second class bus service between Cancun's bus station & their own terminal in Merida via Tixpeual, Tixkokob, Euan, Cacalchen, Izamal, Tunkas, Dzitas, Valladolid, Chemax, Xcan and/or Leona on three different routes. These buses stop anywhere along the road to pick up and drop off people on request."
Cancún,see,Interactive Aquarium,,,,Blvd Kukulcan Km. 12.5 Hotel Zone,Inside La Isla Village Mall in the Hotel Zone.,+52 998 2063311,,,,https://www.interactiveaquariumcancun.com/en/,Daily 09:00-20:00; Marine Presentations 19:00,,,,US$15 basic admissions. More to swim with dolphins and other activities.,21.10967,-86.76449,,,2017-09-04,"Right in the middle of the hotel zone, this small but modern aquarium lets you get up close and personal with aquatic life. You can pet rays, nurse sharks, touch starfish, etc. There is also a chance to swim with captive dolphins in a large pool."
Cancún,do,Xcaret (ecopark),,,,,,,,,,http://www.xcaret.com,,,,,,,,,,,"Xcaret is an eco-archaeological park located about 76 km (46 mi) south of Cancún and less than 7 km (4 mi) south of Playa del Carmen, in the Riviera Maya. Here you can admire tropical flora and fauna typical of the region as well as different expressions of the Mayan culture. In its facilities you can find an archaeological site, snorkeling in underground rivers, beach, butterfly pavilion, orchid greenhouse, regional fauna breeding farm, Mayan village, jaguar island, among others. For additional cost visitors can swim with captive dolphins; enjoy the Temascal and Spa services. At night you can admire the unique night show “Xcaret México Espectacular” which features a variety of performances from ancient Mayan culture to traditional Mexican music and dances. Admission US$80."
Cancún,do,Jeep Adventures,,,,,,,,,,http://www.jeepadventures.com.mx,,,,,,,,,,,"Experience some of the most beautiful parts of Cancún in a self-drive jeep safari. Tour prices ususually include an experienced guide, and the chance to swim or snorkel in underground caves, explore Mayan ruins and visit a jungle reserve."
Cancún,do,Aqua Tours,,,,,,,,,,http://www.aquatours.travel,,,,,,,,,,,Exciting water tour. Choose either a jet ski or two person jet boat for a trip through the lagoon out to snorkel on the reef. Popular tours are the Jungle Tour and the Sailing Quest (Catamarans).
Cancún,do,The Lobster Dinner Cruise,,,,,,,,,,http://www.thelobsterdinner.com,,,,,,,,,,,Take a trip out on the calm lagoon on a beautiful boat with friends you have not met yet. The staff allow you to take part in the fun or settle back and watch the sunset. Steak and lobster is cooked on the boat and is extra tasty when eaten out on the high seas.
Cancún,do,Punta Este Marina,,,,,,,,,,http://www.puntaestemarina.com,,,,,,,,,,,Drive your own boat through the lagoon in the Jungle Tour and sknorkel on the reef. Diving lessons and dive trips to the best dive spots in Cancún such as underwater museum.
Cancún,do,Cancún Yachts Club,,,,boulevardo kukulkan km. 5.8,zona hotelera,+52 998 8495317,,,,http://www.cancunyachtsclub.com,,,,,,,,,,,"Yacht rentals in Cancún. exclusives luxury yachts for rentals tours in all the Cancún areas , snorkeling, diving, swimming the most save water activities in yacht."
Cancún,do,Exotic Rides Mexico,,,,,,+52 998 882 05 58,,,,http://www.exoticrides.mx,,,,,,,,,,,"Driving experiences in some of the most exotic and luxurious cars in the world, race them on a private racetrack in Cancún."
Cancún,do,Always Diving,,,,,,,,,,http://alwaysdiving.com/,,,,,,,,,,,Scuba dive with the most professional team in the area. Competitive prices and a wide catalog of diving programs.
Cancún,do,Diving Center Cancun,,,,"Boulevard Kukulcan, Km 3.2, Zona Hotelera, Marina Chac Chic",,+52 (998) 148 7077,,info@divingcentercancun.com,,http://www.divingcentercancun.com,,,,,,,,,,2016-02-05,Professional PADI certified scuba diving company provides PADI Diving certifications.
Cancún,buy,Market 28,Mercado 28,,,"Xel-ha m 2 13 SM 28, 28,",,,,,,,Daily 09:00-20:00,,,,,21.1617,-86.8343,,,,This is the local market in downtown Cancún. Great shopping for souvenirs. It also has some great Mexican outdoor restaurants. Very cheap and good shopping. Don't forget to bargain.
Cancún,buy,Market 23,Mercado 23,,,"Ciricote 15, SM 23",,,,,,,Daily 07:00-19:00,,,,,21.16799,-86.82802,,,,"This is more of a 'locals' market as most products offered are like groceries, flowers, supplies, etc. Doesn't have the same range as Market 28, but is worth a visit."
Cancún,buy,Plaza Las Americas,,,,"Dialogo Norte-Sur, 7,",Southeast of the roundabout at Av Labna/Sayil and Carr Cancun-Tulum/Av Tulum (Fed Hwy 307,,,,,,Daily 10:00-22:00,,,,,21.1469,-86.8234,,,,"The Plaza de las Americas offers Cinepolis (movie) Theaters, Sears, Chedraui, Liverpool and numerous smaller shops and restaurants in the mall itself and in the immediate surrounding areas not part of the mall."
Cancún,buy,La Isla Cancún Shopping Village,Plaza La Isla,,,"Blvd Kukulcan Km 12.5 Lt 18-10, Zona Hotelera",,+52 998 883-5025,,,,http://www.laislacancun.mx/content/,Daily 10:00-22:00,,,,,21.11076,-86.76356,,,,Shopping mall in the hotel zone. Features hundreds of stores ranging from American brands like Under Armour to Mexican brands like Senor Frogs. There are numerous restaurants including Chili's and McDonald's along with more local Mexican foods.
Cancún,buy,Kukulcan Plaza,,,,"Blvd Kukulcan Km 13, LOCAL 410 y 411A, Zona Hotelera",,+52 998 193-0160,,,,http://www.kukulcanplaza.mx/,Daily 10:00-22:00,,,,,21.1025,-86.7654,,,2017-08-31,"Another mall down the street from 'La Isla' mall in the hotel zone featuring American and Mexican brand names such as Forever 21, GNC and Señor Frog's among other stores and restaurants."
Cancún,buy,Lapis Jewelry Factory,,,,"Blvd. Kukulkan km 11.5 local 100 Int. Plaza Flamingo, Zona Hotelera",,+52 998 110 87 87,,lapiscancun@gmail.com,,http://www.lapis-jewellery.com/,,,,,,,,,,,"You are likely to be offered a coupon for free jewelry at this store. Their website also offers a free gift for individuals who book a shuttle through their website. However, if you do not have any evidence of this, the offer will not be honored. A free shuttle service is offered to take you to the store from your hotel. However, the prices in the store are exorbitant (even at the ""discounted"" rates), and much of the same jewelry is sold by street vendors and hotel gift shops, as well as online. Be sure to investigate other vendors first to get an idea of how much you should pay. One rule of thumb is to buy at 20-30% of the quoted price. For example, if a Mayan calendar pendant is offered to you at the discounted rate of $75, it's actually probably worth about $20. The salespeople will insist that it's worth much more, but stand your ground. If a salesperson agrees to your offer too quickly, you're probably paying too much. In addition, a number of people have reported difficulty obtaining refunds."
Cancún,eat,Mikado,,,,"Blvd. Kukulcán, Retorno Chac L-41, Zona Hotelera",CasaMagna Marriott Cancún Resort,+52 998 881 2000,,,,http://www.mikado.marriottcancunrestaurants.com,17:30-23:00,,,,,,,,,,Japanese and Thai cuisine featuring teppanyaki tables.
Cancún,eat,La Capilla Argentina,,,,"Blvd Kukulcán, Retorno Chac L-41, Zona Hotelera",CasaMagna Marriott Cancún Resort,+52 998 881 2000,,,,http://www.lacapillaargentina.marriottcancunrestaurants.com,,,,,,,,,,,Argentine steakhouse with a Mediterranean flair.
Cancún,eat,Champions Sports Bar,,,,"Blvd Kukulcán, Retorno Chac L-41, Zona Hotelera",CasaMagna Marriott Cancún Resort,+52 998 881 2000,,,,http://www.champions.marriottcancunrestaurants.com,12:00-02:00,,,,,,,,,,Stepped up bar food with all the games on over 40 screens.
Cancún,eat,Simply Seafood,,,,"Blvd Kukulcán, Km 14.5, Lote 40-A, Zona Hotelera",JW Marriott Cancún Resort & Spa,+52 998 848 9600 ext 6637,,,,http://www.simplyseafoodrestaurant.jwmarriottcancunrestaurants.com,,,,,,,,,,,Simply Seafood serves off the boat seafood in traditional Caribbean style.
Cancún,eat,Gustino,,,,"Blvd Kukulcán, Km 14.5, Lote 40-A, Zona Hotelera",JW Marriott Cancún Resort & Spa,+52 998 848 9600 ext 6637,,,,http://www.gustinorestaurant.jwmarriottcancunrestaurants.com,,,,,,,,,,,Gustino has authentic Italian cuisine using the freshest Mediterranean ingredients.
Cancún,eat,The Cove Cancún,,,,,,,,,,http://en.thecovecancun.com/,,,,,,,,,,,"On Playa Langosta (the lobster beach). One of the prettiest and calmest beaches of the Hotel Zone, The Cove offers an excellent variety of dishes. In the morning they have a delicious buffet with sweet bread, fresh fruit, juice, coffee, eggs cooked to order, and other Mexican delights. For lunch, a la carte service. Then at night, a romantic atmosphere with candles, to enjoy the nights of Cancún with a special selected menu with seafood and fish with Caribbean accent, as well as fine cuts, complemented with an ample wine carte."
Cancún,eat,La Habichuela,,,,Margaritas 25,Near Parque de las Palapas,+52 998 884 3158,,info@lahabichuela.com,,http://www.lahabichuela.com/english/index_content.html,,,,,,,,,,,"La Habichuela is a must-visit with its Mexican cuisine, Mayan setting and Caribbean seafood. This restaurant has been open since 1977 and is a legend in Cancún. The romantic, outside garden is a popular place to dine with the decoration of various native trees and plants that create a beautiful illusion of the Mayan ruins under the night sky. La Habicheula received the National Best Restaurant Award and has been a part of the Distinguished Restaurants of North America Organization since 2001."
Cancún,eat,Jimmy Buffett's Margaritaville Cancún,,,,,,+52 998 885 2375,,,,http://www.margaritaville.com.mx/margarita.htm,,,,,,,,,,,"Blvd Kukulcán. This establishment combines the atmosphere of a restaurant, bar, and a mini night club. During the daytime hours, Margaritaville is a restaurant and bar. At night, the place is a combination of the three. With an orange sailboat with images of a plane, shark, and the orange sun, Margaritaville attracts families of all ages as well as party goers."
Cancún,eat,Laguna Grill,,,,Blvd Kukulcán Km 16.5,,+52 998 885 0267,,,,http://www.lagunagrill.com.mx,,,,,,,,,,,"This grill serves seafood, steak, and pasta with a contemporary flair. There is a lush tropical garden at the entrance, intricate handmade tile work on the floor and walls, a small flowing creek that traverses the restaurant, and elegantly-finished tables hewn from trunks of tropical trees. The large terrace is right on the water’s edge. Elegant and comfortable, the next-door Lounge Bar '''Trágara''' offers a wide variety of wines and liquors, while you listen to soft background music and enjoy the charm of the lagoon."
Cancún,eat,Salt,,,,Blvd Kukulcán Km 12,,,,,,,,,,,,,,,,,"Mediterranean cuisine from a wood burning oven, show kitchen and an array of culinary displays. Restaurant overlooks ocean."
Cancún,eat,Las Tortugas,,,,,,+51 998 887 6209,,,,,,,,,,,,,,,"Plaza Las Avenidas. Serving tortas, a kind of Mexican sandwich."
Cancún,eat,La Destileria,,,,"Bulevar Kukulcán Km 12.65, across from Kukulcán Plaza, Cancún Island",,"+51 998 885 1086, +51 998 885 1087",,,,http://www.ladestileria.com.mx/,Daily 13:00-00:00,,,,Main courses US$12-28,,,,,,Combines some of the most authentic Mexican cuisine in the hotel zone with good service and medium price. Very good tequila.
Cancún,eat,Atotonilco,,,,Mercado 28 downtown Cancún,Right across from El Cejas,,,,,,08:00-18:09,,,,US$4-10,,,,,,"An extremely good sampling of Mexican food from all around the country. Excellent value. Nothing fancy but a gastronomical delight. Try the ""Huevos Motuleños""."
Cancún,eat,Silk Asian Bistro,,,,,,,,,,http://www.me-cancun.com/SilkAsianBistro.html,,,,,,,,,,,"Blvd Kukulkan, km. 12. Sushi and sashimi, soy paper vegetarian rolls alongside bolder creations. Teppanyaki stations with theatrical chefs."
Cancún,eat,Pescaditos,,,,Ave Yaxchilán 59,Close to corner of Marañón,,,,,,,,,,,21.161389,-86.829444,,,,"Really nice and laid back seafood restaurant where everything's deep fried. Try the chiles rellenos, possibly the best ones in Cancún."
Cancún,eat,Los de Pescados,,,,Ave Tulum,,,,,,,,,,,,,,,,,Very simple Ttco (specialising in seafood) restaurant. Fish tacos- a few pieces of fried fish with some tortillas and you put your own sauces and condiments on. About M$22 for a taco and M$25 for an ice cold beer.
Cancún,eat,La Panza es Primero,,,,"Plaza Flamingos, Cancún Mexico Hotel zone",,+52 998 252 0776,,,,http://www.lapanzaesprimero.com/,Daily 13:00-00:00,,,,Main courses US$12-28,,,,,,
Cancún,eat,restaurante natura,,,,Boulevard Kukulcan km 9.5,Zona Hotelera,+52 998 8830585,,,,http://www.restaurantelenatura.com,07:30-23:00,,,,,,,,,,"Natura is the only healthy choice restaurant to be found in the hotel zone of Cancún. Fit for Vegetarians and non vegetarians. Over 20 choices of fresh made juices and salads. Service fast and friendly, very clean place and inexpensive. Highly recommended to anyone looking to eat or enjoy some drinks outside in Cancún."
Cancún,eat,Restaurante Labná,,,,Calle Margaritas #25,,+52 998 892 3056,,,,http://labnaonline.com/,12:30-22:00,,,,,,,,,2016-03-03,"One of the only restaurants to serve Yucatecan Mayan cuisine in Cancun. Prices are higher than most Mexican food in downtown Cancun, but it's much cheaper than tourist traps or anything in the hotel zone."
Cancún,eat,Los Tarascos,,,,Av. Tulum 4,,,,,,,16.30-03.00,,,,,,,,,2019-02-18,"Classic Mexican taqueria specializing in tacos al pastor. Very popular with the locals, quite tasty and at a fair price."
Cancún,drink,Señor Frogs,,,,"Blvd. Kukulkan Km. 9, Zona Hotelera",,+52 998 883 3454,,,,http://www.senorfrogscancun.com,,,,,,,,,,,"Señor Frog's is a restaurant by day and a dance club by night, and is one of the most popular spots for vacationers to visit. The restaurant opens up for lunch and serves international types of food such as pasta, chicken and pizza as well as Mexican cuisine all day until midnight. A cover charge of five dollars will get you into the party after 20:00 and includes a souvenir yard glass which you can then pay to get filled with your drink of choice. One of Señor Frog's famous attractions is the water slide that leads from the club out into the lagoon, just for a little bit of fun. As the evening progresses, Señor Frog's becomes less family friendly and more of a party establishment, waitresses will circulate, offering shots of tequila for a price. Waiters are also very ""hands on"", if you are not traveling in a family group, expect them to try to touch, hug, or kiss the female members of the party."
Cancún,drink,O' Ultra Lounge,,,,Hotel Zone,,,,,,,,,,,,,,,,,"is a very sleek New York City type club and can take some time getting in and out of, but has had some great acts like ""Infected Mushroom"" rock the crowd till the wee hours."
Cancún,drink,Basic Discotheque Cancun,,,,"Blvd. Kukulkan Km. 10.3, Zona Hotelera",,+52 998 883-2180,,,,http://bestnewyearsparties.com/basic-discotheque-cancun,,,,,,,,,,,The only nightclub over the lagoon with an amazing half-opened architecture which offers an extraordinary view and the best wet t-shirt and bikini contest of Cancún.
Cancún,drink,Dady'O,,,,"Blvd Kukulkan Km 9.5, Zona Hotelera",Across street from Cocobongo,,,,,http://www.dadyo.com.mx,,,,,,21.133183,-86.7474,,,,"Dady'O has been known to host some of the world's top DJs, including Red Foo (LMFAO), Apl.De.App and Tiësto, features a casual atmosphere, laser shows, pole dancing go go girls and flashing dance floor opening shows."
Cancún,drink,Cocobongo,,,,"Blvd Kukulkan Km 9.5 #30, Zona Hotelera",Across street from Dady'O,,+1 800 841 4636,,,https://www.cocobongo.com/,22:30-05:00,,,,US$75,,,,,,A nightclub featuring a show that has been compared with Las Vegas. More than 50 professionals in scenery. Tickets can be bought online for US$75. If you don't mind waiting to get in exchangeable tickets can be bought from Oxxo for M$1000.
Cancún,drink,Los 4 Elementos,,,,Hotel Xbalamque (Ave Yaxchilan 31),,,,,,,,,,,,,,,,,Try the live music bar Los 4 Elementos. They open and play live music from 23:00 until the last customer leaves. The music is great and prices are significantly lower than those found in the hotel zone clubs.
Cancún,drink,Pericos Restaurante - cantina,,,,Ave Yaxchilan 61,,,,,,,,,,,,,,,,,"Be prepared to join the waiters for some fun games. They also play live music until around 9PM. The atmosphere is fun and relaxing, and prices are reasonable (for example M$230 for a large delicious plate of fish or shrimp). Their dessert serving is quite a show."
Cancún,drink,77 Sports Bars,,,,Ave Yaxchilan,,,,,,,,,,,,,,,,,
Cancún,drink,La Taberna,,,,Ave Yaxchilan,,,,,,,,,,,,,,,,,
Cancún,drink,El Pabilo Cafe,,,,Ave Yaxchilan,,,,,,,,,,,,,,,,,
Cancún,diplomatic-representation,Argentina,,,,"Avenida Carlos Nader 8 Mz 3, SM 5",,+52 998 887 4930,,,,http://www.cmexi.mrecic.gov.ar/,M-F 08:00-15:00,,,,,,,,,2017-09-02,
Cancún,diplomatic-representation,Austria (Honorary),,,,"Edificio Atrium 410, Av. Nichupte, Lote 20, SM 19, Mza 2",,+52 998 881 1970,,,,https://www.bmeia.gv.at/es/embajada-de-austria-en-mexico/sobre-nosotros/consulados-honorarios/,M-F 09:00-14:00,,,,,,,,,2017-09-02,
Cancún,diplomatic-representation,Belgium (Belgica) (Honorary),,,,"Pabellón Caribe, Local PH 6 y 7 – 3er piso, Av Nichupte, SM 19,",,+52 998 892 2512,,,,http://belgicacancun.com/,M-F 09:00-18:00,,,,,,,,,2017-09-02,
Cancún,diplomatic-representation,Canada (Consular Agency),,,,"Blvd Kukulkan Km 12 Oficina E7, Centro Empresarial, Zona Hotelera",,+52 998 883 3360,,,,http://www.canadainternational.gc.ca/mexico-mexique/index.aspx?lang=eng,M-F 09:00-13:00,,,,,,,,,2017-09-02,or call +1 613 996-8885 for emergencies. See this [https://travel.gc.ca/assistance/emergency-assistance link] for more information
Cancún,diplomatic-representation,Cuba,,,,"Percari 17, SM 20",,+52 998 843-243,,,,,,,,,,,,,,2017-10-26,
Cancún,diplomatic-representation,Denmark (Honorary),,,,"Plaza Santa Fe, Blvd Luis Donaldo Colosio Km 12.5, SM 301",,+52 998 848-8900,,,,http://mexico.um.dk/en/about-us/consulates/cancun,M-F 10:00-17:00,,,,,,,,,2017-10-26,
Cancún,diplomatic-representation,Germany (Alemania) (Honorary),,,,"Punta Conoco 36 SM 24,",,+52 998 884 1598,,,,http://www.mexiko.diplo.de/,,,,,,,,,,2017-09-02,
Cancún,diplomatic-representation,Netherlands (Honorary),,,,"Hotel Ibis 3er Planta, Ave Acanceh Mz2, Lot 3, Planta 3B, SM 11",,+52 998 500-1653,,,,https://www.netherlandsandyou.nl/your-country-and-the-netherlands/mexico/about-us/the-netherlands-honorary-consulate-in-cancun,By appointment only,,,,,,,,,2017-10-26,
Cancún,diplomatic-representation,Portugal,,,,"Guanabana 40, SM 25, Manzana 13, Lote 11, 2do. Piso, Depto.2",,+52 998 8842735,,,,,,,,,,,,,,2017-09-02,
Cancún,diplomatic-representation,Sweden (Honorary),,,,"Omni Cancun Hotels & Villas, Blvd Kukulkan Km 16.5, Lote 48, MZA 53",Blvd Kukulkan Km 16.5,"+52 998 848-89-00, +52 998 275-20-01 (for emergencies only)",,,,,,,,,,,,,,2017-10-26,
Cancún,diplomatic-representation,United Kingdom (Honorary),,,,"The Royal Sands, Blvd Kulkukan Km 13.5, Zona Hotelera",,+52 998 881 0100,,,,,,,,,,,,,,2017-09-02,
Cancún,diplomatic-representation,United States (Consular Agency),,,,"Blvd Kukulcan Km 13 Zona Hotelera, Torre La Europea, Despacho 301",,+52 999 942-5700,,ConAgencyCancun@state.gov,+52 998 883 1373,https://mx.usembassy.gov/embassy-consulates/merida/consular-agencies/,M-F 08:30-13:00,,,,,,,,,,"This consular agency part of the [https://mx.usembassy.gov/embassy-consulates/merida/ US Consulate General in Merida] to handle emergency US citizen services, passport applications, birth certificates, and notarials in Cancun. Most services require an appointment. Visa services are not available here, but rather at the consulate in Mérida."
Cuiabá,eat,Café Cancun,,,,,,,,,,http://www.cafecancun.com.br/cuiaba.html,,,,,,,,,,,"It's called ""funny restaurant"", an entertainment house to have a fun eating, drinking, and dancing with Mexican food and wide variety of drinks. The sound is salsa, mambo, and merengue."
Isla Mujeres,see,Tortugranja,Turtle Farm,,,Sac Bajo,North of Playa Paraiso,+52 998 877 0595,,turtfarm@cancun.com.mx,,,9AM-5PM,,,,M$30,,,,,2015-12-15,"Government sponsored hatchery for endangered sea turtles. See lots of baby turtles as well as medium-sized turtles, seahorses, etc. inside. Outside there are older turtles and even sharks. Food for the older turtles costs M$20. Taxis from the ferry port cost M$75 each way to Tortugranja."
Kingston (Massachusetts),eat,Cancun Family Mexican Restaurant,,,,145 Main St,,,,,,http://cancunkingston.com/,,,,,,41.98866,-70.71865,,,,"High-quality, authentic Mexican food and margarita bar. Family-friendly."
Playa del Carmen,other,eTransfers,Playa del Carmen Transportation,,,,,+52 998 980 0259,,bookings@etransfers.net,,https://www.cancun-shuttle-transportation.com/destinations/playa-del-carmen-transportation,,,,,,,,,,2019-01-15,

`.replace(/,+/g, ",");

const nameAry =
  // tokenizer.sentences(p, { sanitize: true })
  p
    .split("\n")
    .filter(Boolean)
    .filter((x) => x.includes("cancun") || x.includes("Cancún"));
//   .sort(() => 0.5 - Math.random())
//   .slice(0, 14);

const sorted = nameAry.sort(
  (a, b) =>
    stringSimilarity.compareTwoStrings(nameAry[0], a) -
    stringSimilarity.compareTwoStrings(nameAry[0], b)
);

// console.log(stringSimilarity.findBestMatch(nameAry[0], nameAry));
sorted.forEach((line) => {
  console.log(line + "\n");
});
